# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adjust_contrast_QV_dialog.ui'
#
# Created: Sun Jul 12 19:52:45 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(607, 433)
        self.horizontalLayout = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget_1 = QtGui.QWidget(Dialog)
        self.widget_1.setMaximumSize(QtCore.QSize(16777215, 97))
        self.widget_1.setObjectName(_fromUtf8("widget_1"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.widget_1)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.viw_label_1 = QtGui.QLabel(self.widget_1)
        self.viw_label_1.setObjectName(_fromUtf8("viw_label_1"))
        self.verticalLayout_18.addWidget(self.viw_label_1)
        self.horizontalLayout_26.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.high_contrast_label_1 = QtGui.QLabel(self.widget_1)
        self.high_contrast_label_1.setObjectName(_fromUtf8("high_contrast_label_1"))
        self.horizontalLayout_27.addWidget(self.high_contrast_label_1)
        self.high_contrast_slider_1 = QtGui.QSlider(self.widget_1)
        self.high_contrast_slider_1.setOrientation(QtCore.Qt.Horizontal)
        self.high_contrast_slider_1.setObjectName(_fromUtf8("high_contrast_slider_1"))
        self.horizontalLayout_27.addWidget(self.high_contrast_slider_1)
        self.high_spin_box_1 = QtGui.QSpinBox(self.widget_1)
        self.high_spin_box_1.setObjectName(_fromUtf8("high_spin_box_1"))
        self.horizontalLayout_27.addWidget(self.high_spin_box_1)
        self.verticalLayout_19.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.low_spin_box_1 = QtGui.QSpinBox(self.widget_1)
        self.low_spin_box_1.setObjectName(_fromUtf8("low_spin_box_1"))
        self.horizontalLayout_28.addWidget(self.low_spin_box_1)
        self.low_contrast_slider_1 = QtGui.QSlider(self.widget_1)
        self.low_contrast_slider_1.setOrientation(QtCore.Qt.Horizontal)
        self.low_contrast_slider_1.setObjectName(_fromUtf8("low_contrast_slider_1"))
        self.horizontalLayout_28.addWidget(self.low_contrast_slider_1)
        self.low_contrast_label_1 = QtGui.QLabel(self.widget_1)
        self.low_contrast_label_1.setObjectName(_fromUtf8("low_contrast_label_1"))
        self.horizontalLayout_28.addWidget(self.low_contrast_label_1)
        self.verticalLayout_19.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_26.addLayout(self.verticalLayout_19)
        self.verticalLayout_17.addLayout(self.horizontalLayout_26)
        self.line_1 = QtGui.QFrame(self.widget_1)
        self.line_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName(_fromUtf8("line_1"))
        self.verticalLayout_17.addWidget(self.line_1)
        self.horizontalLayout_14.addLayout(self.verticalLayout_17)
        self.verticalLayout.addWidget(self.widget_1)
        self.widget_2 = QtGui.QWidget(Dialog)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 97))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.viw_label_2 = QtGui.QLabel(self.widget_2)
        self.viw_label_2.setObjectName(_fromUtf8("viw_label_2"))
        self.verticalLayout_21.addWidget(self.viw_label_2)
        self.horizontalLayout_29.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.high_contrast_label_2 = QtGui.QLabel(self.widget_2)
        self.high_contrast_label_2.setObjectName(_fromUtf8("high_contrast_label_2"))
        self.horizontalLayout_30.addWidget(self.high_contrast_label_2)
        self.high_contrast_slider_2 = QtGui.QSlider(self.widget_2)
        self.high_contrast_slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.high_contrast_slider_2.setObjectName(_fromUtf8("high_contrast_slider_2"))
        self.horizontalLayout_30.addWidget(self.high_contrast_slider_2)
        self.high_spin_box_2 = QtGui.QSpinBox(self.widget_2)
        self.high_spin_box_2.setObjectName(_fromUtf8("high_spin_box_2"))
        self.horizontalLayout_30.addWidget(self.high_spin_box_2)
        self.verticalLayout_22.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.low_spin_box_2 = QtGui.QSpinBox(self.widget_2)
        self.low_spin_box_2.setObjectName(_fromUtf8("low_spin_box_2"))
        self.horizontalLayout_31.addWidget(self.low_spin_box_2)
        self.low_contrast_slider_2 = QtGui.QSlider(self.widget_2)
        self.low_contrast_slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.low_contrast_slider_2.setObjectName(_fromUtf8("low_contrast_slider_2"))
        self.horizontalLayout_31.addWidget(self.low_contrast_slider_2)
        self.low_contrast_label_2 = QtGui.QLabel(self.widget_2)
        self.low_contrast_label_2.setObjectName(_fromUtf8("low_contrast_label_2"))
        self.horizontalLayout_31.addWidget(self.low_contrast_label_2)
        self.verticalLayout_22.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_29.addLayout(self.verticalLayout_22)
        self.verticalLayout_20.addLayout(self.horizontalLayout_29)
        self.line_2 = QtGui.QFrame(self.widget_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_20.addWidget(self.line_2)
        self.horizontalLayout_15.addLayout(self.verticalLayout_20)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtGui.QWidget(Dialog)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 97))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_16.setMargin(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.viw_label_3 = QtGui.QLabel(self.widget_3)
        self.viw_label_3.setObjectName(_fromUtf8("viw_label_3"))
        self.verticalLayout_24.addWidget(self.viw_label_3)
        self.horizontalLayout_32.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.high_contrast_label_3 = QtGui.QLabel(self.widget_3)
        self.high_contrast_label_3.setObjectName(_fromUtf8("high_contrast_label_3"))
        self.horizontalLayout_33.addWidget(self.high_contrast_label_3)
        self.high_contrast_slider_3 = QtGui.QSlider(self.widget_3)
        self.high_contrast_slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.high_contrast_slider_3.setObjectName(_fromUtf8("high_contrast_slider_3"))
        self.horizontalLayout_33.addWidget(self.high_contrast_slider_3)
        self.high_spin_box_3 = QtGui.QSpinBox(self.widget_3)
        self.high_spin_box_3.setObjectName(_fromUtf8("high_spin_box_3"))
        self.horizontalLayout_33.addWidget(self.high_spin_box_3)
        self.verticalLayout_25.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.low_spin_box_3 = QtGui.QSpinBox(self.widget_3)
        self.low_spin_box_3.setObjectName(_fromUtf8("low_spin_box_3"))
        self.horizontalLayout_34.addWidget(self.low_spin_box_3)
        self.low_contrast_slider_3 = QtGui.QSlider(self.widget_3)
        self.low_contrast_slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.low_contrast_slider_3.setObjectName(_fromUtf8("low_contrast_slider_3"))
        self.horizontalLayout_34.addWidget(self.low_contrast_slider_3)
        self.low_contrast_label_3 = QtGui.QLabel(self.widget_3)
        self.low_contrast_label_3.setObjectName(_fromUtf8("low_contrast_label_3"))
        self.horizontalLayout_34.addWidget(self.low_contrast_label_3)
        self.verticalLayout_25.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_32.addLayout(self.verticalLayout_25)
        self.verticalLayout_23.addLayout(self.horizontalLayout_32)
        self.line_3 = QtGui.QFrame(self.widget_3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_23.addWidget(self.line_3)
        self.horizontalLayout_16.addLayout(self.verticalLayout_23)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = QtGui.QWidget(Dialog)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 97))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_17.setMargin(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.viw_label_4 = QtGui.QLabel(self.widget_4)
        self.viw_label_4.setObjectName(_fromUtf8("viw_label_4"))
        self.verticalLayout_27.addWidget(self.viw_label_4)
        self.horizontalLayout_35.addLayout(self.verticalLayout_27)
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.high_contrast_label_4 = QtGui.QLabel(self.widget_4)
        self.high_contrast_label_4.setObjectName(_fromUtf8("high_contrast_label_4"))
        self.horizontalLayout_36.addWidget(self.high_contrast_label_4)
        self.high_contrast_slider_4 = QtGui.QSlider(self.widget_4)
        self.high_contrast_slider_4.setOrientation(QtCore.Qt.Horizontal)
        self.high_contrast_slider_4.setObjectName(_fromUtf8("high_contrast_slider_4"))
        self.horizontalLayout_36.addWidget(self.high_contrast_slider_4)
        self.high_spin_box_4 = QtGui.QSpinBox(self.widget_4)
        self.high_spin_box_4.setObjectName(_fromUtf8("high_spin_box_4"))
        self.horizontalLayout_36.addWidget(self.high_spin_box_4)
        self.verticalLayout_28.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.low_spin_box_4 = QtGui.QSpinBox(self.widget_4)
        self.low_spin_box_4.setObjectName(_fromUtf8("low_spin_box_4"))
        self.horizontalLayout_37.addWidget(self.low_spin_box_4)
        self.low_contrast_slider_4 = QtGui.QSlider(self.widget_4)
        self.low_contrast_slider_4.setOrientation(QtCore.Qt.Horizontal)
        self.low_contrast_slider_4.setObjectName(_fromUtf8("low_contrast_slider_4"))
        self.horizontalLayout_37.addWidget(self.low_contrast_slider_4)
        self.low_contrast_label_4 = QtGui.QLabel(self.widget_4)
        self.low_contrast_label_4.setObjectName(_fromUtf8("low_contrast_label_4"))
        self.horizontalLayout_37.addWidget(self.low_contrast_label_4)
        self.verticalLayout_28.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_35.addLayout(self.verticalLayout_28)
        self.verticalLayout_26.addLayout(self.horizontalLayout_35)
        self.line_4 = QtGui.QFrame(self.widget_4)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_26.addWidget(self.line_4)
        self.horizontalLayout_17.addLayout(self.verticalLayout_26)
        self.verticalLayout.addWidget(self.widget_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.viw_label_1.setText(_translate("Dialog", "View1:", None))
        self.high_contrast_label_1.setText(_translate("Dialog", "High", None))
        self.low_contrast_label_1.setText(_translate("Dialog", "Low", None))
        self.viw_label_2.setText(_translate("Dialog", "View2:", None))
        self.high_contrast_label_2.setText(_translate("Dialog", "High", None))
        self.low_contrast_label_2.setText(_translate("Dialog", "Low", None))
        self.viw_label_3.setText(_translate("Dialog", "View3:", None))
        self.high_contrast_label_3.setText(_translate("Dialog", "High", None))
        self.low_contrast_label_3.setText(_translate("Dialog", "Low", None))
        self.viw_label_4.setText(_translate("Dialog", "View4:", None))
        self.high_contrast_label_4.setText(_translate("Dialog", "High", None))
        self.low_contrast_label_4.setText(_translate("Dialog", "Low", None))

