# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quad_view_dialog.ui'
#
# Created: Sun Jul 12 19:52:53 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1071, 710)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.FullFrame = QtGui.QFrame(Dialog)
        self.FullFrame.setMinimumSize(QtCore.QSize(512, 512))
        self.FullFrame.setMaximumSize(QtCore.QSize(512, 512))
        self.FullFrame.setAutoFillBackground(False)
        self.FullFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.FullFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.FullFrame.setObjectName(_fromUtf8("FullFrame"))
        self.horizontalLayout_2.addWidget(self.FullFrame)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.QV_Params_Holder = QtGui.QWidget(Dialog)
        self.QV_Params_Holder.setObjectName(_fromUtf8("QV_Params_Holder"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.QV_Params_Holder)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.CombinedFrame = QtGui.QFrame(self.QV_Params_Holder)
        self.CombinedFrame.setMinimumSize(QtCore.QSize(256, 256))
        self.CombinedFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CombinedFrame.setAutoFillBackground(False)
        self.CombinedFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.CombinedFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.CombinedFrame.setObjectName(_fromUtf8("CombinedFrame"))
        self.horizontalLayout_4.addWidget(self.CombinedFrame)
        self.paramaters_widget = QtGui.QWidget(self.QV_Params_Holder)
        self.paramaters_widget.setMinimumSize(QtCore.QSize(143, 257))
        self.paramaters_widget.setMaximumSize(QtCore.QSize(143, 257))
        self.paramaters_widget.setObjectName(_fromUtf8("paramaters_widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.paramaters_widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.buttonBox = QtGui.QDialogButtonBox(self.paramaters_widget)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ParamatersLabel = QtGui.QLabel(self.paramaters_widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ParamatersLabel.setFont(font)
        self.ParamatersLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ParamatersLabel.setObjectName(_fromUtf8("ParamatersLabel"))
        self.verticalLayout.addWidget(self.ParamatersLabel)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.numViewsLabel = QtGui.QLabel(self.paramaters_widget)
        self.numViewsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numViewsLabel.setObjectName(_fromUtf8("numViewsLabel"))
        self.horizontalLayout_9.addWidget(self.numViewsLabel)
        self.numViews = QtGui.QSpinBox(self.paramaters_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numViews.sizePolicy().hasHeightForWidth())
        self.numViews.setSizePolicy(sizePolicy)
        self.numViews.setMinimum(1)
        self.numViews.setMaximum(4)
        self.numViews.setProperty("value", 2)
        self.numViews.setObjectName(_fromUtf8("numViews"))
        self.horizontalLayout_9.addWidget(self.numViews)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.QVsizeXLabel = QtGui.QLabel(self.paramaters_widget)
        self.QVsizeXLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.QVsizeXLabel.setObjectName(_fromUtf8("QVsizeXLabel"))
        self.horizontalLayout_5.addWidget(self.QVsizeXLabel)
        self.QVSizeX = QtGui.QSpinBox(self.paramaters_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QVSizeX.sizePolicy().hasHeightForWidth())
        self.QVSizeX.setSizePolicy(sizePolicy)
        self.QVSizeX.setMinimum(1)
        self.QVSizeX.setMaximum(100000)
        self.QVSizeX.setSingleStep(1)
        self.QVSizeX.setProperty("value", 256)
        self.QVSizeX.setObjectName(_fromUtf8("QVSizeX"))
        self.horizontalLayout_5.addWidget(self.QVSizeX)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.QVSizeYLabel = QtGui.QLabel(self.paramaters_widget)
        self.QVSizeYLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.QVSizeYLabel.setObjectName(_fromUtf8("QVSizeYLabel"))
        self.horizontalLayout_8.addWidget(self.QVSizeYLabel)
        self.QVSizeY = QtGui.QSpinBox(self.paramaters_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QVSizeY.sizePolicy().hasHeightForWidth())
        self.QVSizeY.setSizePolicy(sizePolicy)
        self.QVSizeY.setMinimum(1)
        self.QVSizeY.setMaximum(100000)
        self.QVSizeY.setProperty("value", 256)
        self.QVSizeY.setObjectName(_fromUtf8("QVSizeY"))
        self.horizontalLayout_8.addWidget(self.QVSizeY)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.save_parms_btn = QtGui.QPushButton(self.paramaters_widget)
        self.save_parms_btn.setObjectName(_fromUtf8("save_parms_btn"))
        self.verticalLayout_3.addWidget(self.save_parms_btn)
        self.load_parms_btn = QtGui.QPushButton(self.paramaters_widget)
        self.load_parms_btn.setObjectName(_fromUtf8("load_parms_btn"))
        self.verticalLayout_3.addWidget(self.load_parms_btn)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4.addWidget(self.paramaters_widget)
        self.verticalLayout_4.addWidget(self.QV_Params_Holder)
        self.dials_widget = QtGui.QWidget(Dialog)
        self.dials_widget.setMaximumSize(QtCore.QSize(16777215, 400))
        self.dials_widget.setObjectName(_fromUtf8("dials_widget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dials_widget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget_1 = QtGui.QWidget(self.dials_widget)
        self.widget_1.setMaximumSize(QtCore.QSize(16777215, 97))
        self.widget_1.setObjectName(_fromUtf8("widget_1"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.widget_1)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.viw_label_1 = QtGui.QLabel(self.widget_1)
        self.viw_label_1.setObjectName(_fromUtf8("viw_label_1"))
        self.verticalLayout_18.addWidget(self.viw_label_1)
        self.colObj_1 = QtGui.QPushButton(self.widget_1)
        self.colObj_1.setText(_fromUtf8(""))
        self.colObj_1.setObjectName(_fromUtf8("colObj_1"))
        self.verticalLayout_18.addWidget(self.colObj_1)
        self.horizontalLayout_26.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.high_contrast_label_1 = QtGui.QLabel(self.widget_1)
        self.high_contrast_label_1.setObjectName(_fromUtf8("high_contrast_label_1"))
        self.horizontalLayout_27.addWidget(self.high_contrast_label_1)
        self.high_contrast_slider_1 = QtGui.QSlider(self.widget_1)
        self.high_contrast_slider_1.setOrientation(QtCore.Qt.Horizontal)
        self.high_contrast_slider_1.setObjectName(_fromUtf8("high_contrast_slider_1"))
        self.horizontalLayout_27.addWidget(self.high_contrast_slider_1)
        self.high_spin_box_1 = QtGui.QSpinBox(self.widget_1)
        self.high_spin_box_1.setObjectName(_fromUtf8("high_spin_box_1"))
        self.horizontalLayout_27.addWidget(self.high_spin_box_1)
        self.verticalLayout_19.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.low_spin_box_1 = QtGui.QSpinBox(self.widget_1)
        self.low_spin_box_1.setObjectName(_fromUtf8("low_spin_box_1"))
        self.horizontalLayout_28.addWidget(self.low_spin_box_1)
        self.low_contrast_slider_1 = QtGui.QSlider(self.widget_1)
        self.low_contrast_slider_1.setOrientation(QtCore.Qt.Horizontal)
        self.low_contrast_slider_1.setObjectName(_fromUtf8("low_contrast_slider_1"))
        self.horizontalLayout_28.addWidget(self.low_contrast_slider_1)
        self.low_contrast_label_1 = QtGui.QLabel(self.widget_1)
        self.low_contrast_label_1.setObjectName(_fromUtf8("low_contrast_label_1"))
        self.horizontalLayout_28.addWidget(self.low_contrast_label_1)
        self.verticalLayout_19.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_26.addLayout(self.verticalLayout_19)
        self.verticalLayout_17.addLayout(self.horizontalLayout_26)
        self.line_1 = QtGui.QFrame(self.widget_1)
        self.line_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName(_fromUtf8("line_1"))
        self.verticalLayout_17.addWidget(self.line_1)
        self.horizontalLayout_14.addLayout(self.verticalLayout_17)
        self.verticalLayout_2.addWidget(self.widget_1)
        self.widget_2 = QtGui.QWidget(self.dials_widget)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 97))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.viw_label_2 = QtGui.QLabel(self.widget_2)
        self.viw_label_2.setObjectName(_fromUtf8("viw_label_2"))
        self.verticalLayout_21.addWidget(self.viw_label_2)
        self.colObj_2 = QtGui.QPushButton(self.widget_2)
        self.colObj_2.setText(_fromUtf8(""))
        self.colObj_2.setObjectName(_fromUtf8("colObj_2"))
        self.verticalLayout_21.addWidget(self.colObj_2)
        self.horizontalLayout_29.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.high_contrast_label_2 = QtGui.QLabel(self.widget_2)
        self.high_contrast_label_2.setObjectName(_fromUtf8("high_contrast_label_2"))
        self.horizontalLayout_30.addWidget(self.high_contrast_label_2)
        self.high_contrast_slider_2 = QtGui.QSlider(self.widget_2)
        self.high_contrast_slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.high_contrast_slider_2.setObjectName(_fromUtf8("high_contrast_slider_2"))
        self.horizontalLayout_30.addWidget(self.high_contrast_slider_2)
        self.high_spin_box_2 = QtGui.QSpinBox(self.widget_2)
        self.high_spin_box_2.setObjectName(_fromUtf8("high_spin_box_2"))
        self.horizontalLayout_30.addWidget(self.high_spin_box_2)
        self.verticalLayout_22.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.low_spin_box_2 = QtGui.QSpinBox(self.widget_2)
        self.low_spin_box_2.setObjectName(_fromUtf8("low_spin_box_2"))
        self.horizontalLayout_31.addWidget(self.low_spin_box_2)
        self.low_contrast_slider_2 = QtGui.QSlider(self.widget_2)
        self.low_contrast_slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.low_contrast_slider_2.setObjectName(_fromUtf8("low_contrast_slider_2"))
        self.horizontalLayout_31.addWidget(self.low_contrast_slider_2)
        self.low_contrast_label_2 = QtGui.QLabel(self.widget_2)
        self.low_contrast_label_2.setObjectName(_fromUtf8("low_contrast_label_2"))
        self.horizontalLayout_31.addWidget(self.low_contrast_label_2)
        self.verticalLayout_22.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_29.addLayout(self.verticalLayout_22)
        self.verticalLayout_20.addLayout(self.horizontalLayout_29)
        self.line_2 = QtGui.QFrame(self.widget_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_20.addWidget(self.line_2)
        self.horizontalLayout_15.addLayout(self.verticalLayout_20)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtGui.QWidget(self.dials_widget)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 97))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_16.setMargin(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.viw_label_3 = QtGui.QLabel(self.widget_3)
        self.viw_label_3.setObjectName(_fromUtf8("viw_label_3"))
        self.verticalLayout_24.addWidget(self.viw_label_3)
        self.colObj_3 = QtGui.QPushButton(self.widget_3)
        self.colObj_3.setText(_fromUtf8(""))
        self.colObj_3.setObjectName(_fromUtf8("colObj_3"))
        self.verticalLayout_24.addWidget(self.colObj_3)
        self.horizontalLayout_32.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.high_contrast_label_3 = QtGui.QLabel(self.widget_3)
        self.high_contrast_label_3.setObjectName(_fromUtf8("high_contrast_label_3"))
        self.horizontalLayout_33.addWidget(self.high_contrast_label_3)
        self.high_contrast_slider_3 = QtGui.QSlider(self.widget_3)
        self.high_contrast_slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.high_contrast_slider_3.setObjectName(_fromUtf8("high_contrast_slider_3"))
        self.horizontalLayout_33.addWidget(self.high_contrast_slider_3)
        self.high_spin_box_3 = QtGui.QSpinBox(self.widget_3)
        self.high_spin_box_3.setObjectName(_fromUtf8("high_spin_box_3"))
        self.horizontalLayout_33.addWidget(self.high_spin_box_3)
        self.verticalLayout_25.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.low_spin_box_3 = QtGui.QSpinBox(self.widget_3)
        self.low_spin_box_3.setObjectName(_fromUtf8("low_spin_box_3"))
        self.horizontalLayout_34.addWidget(self.low_spin_box_3)
        self.low_contrast_slider_3 = QtGui.QSlider(self.widget_3)
        self.low_contrast_slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.low_contrast_slider_3.setObjectName(_fromUtf8("low_contrast_slider_3"))
        self.horizontalLayout_34.addWidget(self.low_contrast_slider_3)
        self.low_contrast_label_3 = QtGui.QLabel(self.widget_3)
        self.low_contrast_label_3.setObjectName(_fromUtf8("low_contrast_label_3"))
        self.horizontalLayout_34.addWidget(self.low_contrast_label_3)
        self.verticalLayout_25.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_32.addLayout(self.verticalLayout_25)
        self.verticalLayout_23.addLayout(self.horizontalLayout_32)
        self.line_3 = QtGui.QFrame(self.widget_3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_23.addWidget(self.line_3)
        self.horizontalLayout_16.addLayout(self.verticalLayout_23)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtGui.QWidget(self.dials_widget)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 97))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_17.setMargin(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.viw_label_4 = QtGui.QLabel(self.widget_4)
        self.viw_label_4.setObjectName(_fromUtf8("viw_label_4"))
        self.verticalLayout_27.addWidget(self.viw_label_4)
        self.colObj_4 = QtGui.QPushButton(self.widget_4)
        self.colObj_4.setText(_fromUtf8(""))
        self.colObj_4.setObjectName(_fromUtf8("colObj_4"))
        self.verticalLayout_27.addWidget(self.colObj_4)
        self.horizontalLayout_35.addLayout(self.verticalLayout_27)
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.high_contrast_label_4 = QtGui.QLabel(self.widget_4)
        self.high_contrast_label_4.setObjectName(_fromUtf8("high_contrast_label_4"))
        self.horizontalLayout_36.addWidget(self.high_contrast_label_4)
        self.high_contrast_slider_4 = QtGui.QSlider(self.widget_4)
        self.high_contrast_slider_4.setOrientation(QtCore.Qt.Horizontal)
        self.high_contrast_slider_4.setObjectName(_fromUtf8("high_contrast_slider_4"))
        self.horizontalLayout_36.addWidget(self.high_contrast_slider_4)
        self.high_spin_box_4 = QtGui.QSpinBox(self.widget_4)
        self.high_spin_box_4.setObjectName(_fromUtf8("high_spin_box_4"))
        self.horizontalLayout_36.addWidget(self.high_spin_box_4)
        self.verticalLayout_28.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.low_spin_box_4 = QtGui.QSpinBox(self.widget_4)
        self.low_spin_box_4.setObjectName(_fromUtf8("low_spin_box_4"))
        self.horizontalLayout_37.addWidget(self.low_spin_box_4)
        self.low_contrast_slider_4 = QtGui.QSlider(self.widget_4)
        self.low_contrast_slider_4.setOrientation(QtCore.Qt.Horizontal)
        self.low_contrast_slider_4.setObjectName(_fromUtf8("low_contrast_slider_4"))
        self.horizontalLayout_37.addWidget(self.low_contrast_slider_4)
        self.low_contrast_label_4 = QtGui.QLabel(self.widget_4)
        self.low_contrast_label_4.setObjectName(_fromUtf8("low_contrast_label_4"))
        self.horizontalLayout_37.addWidget(self.low_contrast_label_4)
        self.verticalLayout_28.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_35.addLayout(self.verticalLayout_28)
        self.verticalLayout_26.addLayout(self.horizontalLayout_35)
        self.line_4 = QtGui.QFrame(self.widget_4)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_26.addWidget(self.line_4)
        self.horizontalLayout_17.addLayout(self.verticalLayout_26)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addWidget(self.dials_widget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.ParamatersLabel.setText(_translate("Dialog", "Paramaters", None))
        self.numViewsLabel.setText(_translate("Dialog", "# Views:", None))
        self.QVsizeXLabel.setText(_translate("Dialog", "size X:", None))
        self.QVSizeYLabel.setText(_translate("Dialog", "size Y:", None))
        self.save_parms_btn.setText(_translate("Dialog", "Save Paramaters", None))
        self.load_parms_btn.setText(_translate("Dialog", "Load Paramaters", None))
        self.viw_label_1.setText(_translate("Dialog", "View1:", None))
        self.high_contrast_label_1.setText(_translate("Dialog", "High", None))
        self.low_contrast_label_1.setText(_translate("Dialog", "Low", None))
        self.viw_label_2.setText(_translate("Dialog", "View2:", None))
        self.high_contrast_label_2.setText(_translate("Dialog", "High", None))
        self.low_contrast_label_2.setText(_translate("Dialog", "Low", None))
        self.viw_label_3.setText(_translate("Dialog", "View3:", None))
        self.high_contrast_label_3.setText(_translate("Dialog", "High", None))
        self.low_contrast_label_3.setText(_translate("Dialog", "Low", None))
        self.viw_label_4.setText(_translate("Dialog", "View4:", None))
        self.high_contrast_label_4.setText(_translate("Dialog", "High", None))
        self.low_contrast_label_4.setText(_translate("Dialog", "Low", None))

